name: "PRScope"
description: "AI-powered pull request reviews that actually help."
author: "KinanNasri"

inputs:
  config_path:
    description: "Path to prscope.config.json (relative to repo root)"
    required: false
    default: ""
  provider:
    description: "LLM provider: openai | anthropic | openai-compat | ollama"
    required: false
  model:
    description: "Model identifier (e.g. gpt-4.1, claude-sonnet-4-20250514)"
    required: false
  api_key_env:
    description: "Environment variable name containing the API key"
    required: false
  base_url:
    description: "Custom base URL for the LLM API"
    required: false
  profile:
    description: "Review profile: balanced | security | performance | strict"
    required: false
  comment_mode:
    description: "Comment mode: summary-only | inline+summary"
    required: false
  max_files:
    description: "Maximum number of files to review"
    required: false
  max_diff_bytes:
    description: "Maximum total diff size in bytes"
    required: false

runs:
  using: "node20"
  main: "dist/index.cjs"

branding:
  icon: "search"
  color: "blue"
